---
name: 'Run Acceptance Tests'
description: 'Run Acceptance Tests'
runs:
  using: 'composite'
  steps:
    - name: Run Acceptance Tests
      run: |
        Import-Module $env:ChocolateyInstall\helpers\chocolateyProfile.psm1
        refreshenv
        Import-Module -Name PSDesiredStateConfiguration -Force
        Import-Module -Name .\src\Puppet.Dsc\puppet.dsc.psd1 -Force
        $null = Get-Command -Module Puppet.Dsc

        $ErrorActionPreference = "Stop"
        $TestParameters = @{
          TestPath         = @((Resolve-Path .\acceptance))
          ResultsPath      = "${{ matrix.results_file }}"
          Tag              = "${{ matrix.tag }}"
          PwshLibSource    = "${{ matrix.pwshlib_source }}"
          PwshLibRepo      = "${{ matrix.pwshlib_repo }}"
          PwshLibReference = "${{ matrix.pwshlib_ref }}"
        }

        $Results = .\scripts\invoke_tests.ps1 @TestParameters
        if ($Results.FailedCount -gt 0) {
          throw "$($Results.FailedCount) tests failed."
        }
      shell: powershell
